# Gives the names and SQL commands for the database table columns

class DatabaseColumn():
    '''Column to be used in a database.

    name -- the name of the column
    cmd -- definition of the column where the name is formatted in.  For example
        \'{} INTEGER NOT NULL\'
    '''

    def __init__(self, name, cmd):
        self.name = name
        self.cmd = cmd.format(name)


a1_model_firmid = DatabaseColumn('a1_model_firmid', '')
a1_prdns_with_alias_name = DatabaseColumn('a1_prdns_with_alias_name', '{} INTEGER')
a1_prdns_with_standardized_name = DatabaseColumn('a1_prdns_with_standardized_name', '{} INTEGER')
abs_cw_yr = DatabaseColumn('abs_cw_yr', '{} INTEGER')
abs_emp_yr = DatabaseColumn('abs_emp_yr', '{} INTEGER')
abs_yr_diff = DatabaseColumn('abs_yr_diff', '')
alias_name = DatabaseColumn('alias_name', '{} TEXT')
alias_on_prdn_count = DatabaseColumn('alias_on_prdn_count', '{} INTEGER')
app_yr = DatabaseColumn('app_yr', '{} INTEGER NOT NULL')
assg_city = DatabaseColumn('assg_city', '{} TEXT')
assg_ctry = DatabaseColumn('assg_ctry', '{} TEXT')
assg_ein = DatabaseColumn('assg_ein', '')
assg_ein = DatabaseColumn('assg_ein', '')
assg_firmid = DatabaseColumn('assg_firmid', '')
assg_name = DatabaseColumn('assg_name', '{} TEXT NOT NULL')
assg_name_xml = DatabaseColumn('assg_name_xml', '{} TEXT')
assg_name_clean = DatabaseColumn('assg_name_clean', '{} TEXT')
assg_name_raw = DatabaseColumn('assg_name_raw', '{} TEXT')
assg_name_inferred = DatabaseColumn('assg_name_inferred', '{} TEXT')
assg_num = DatabaseColumn('assg_num', '')
assg_prdn = DatabaseColumn('assg_prdn', '')
assg_seq = DatabaseColumn('assg_seq', '{} INTEGER NOT NULL')
assg_st = DatabaseColumn('assg_st', '{} TEXT')
assg_st_inferred = DatabaseColumn('assg_st_inferred', '{} TEXT')
assg_type = DatabaseColumn('assg_type', '{} TEXT')
br_yr = DatabaseColumn('br_yr', '{} INTEGER NOT NULL')
corrected_name = DatabaseColumn('corrected_name', '{} TEXT')
count = DatabaseColumn('count', 'TEXT DEFAULT ""')
country = DatabaseColumn('country', '{} TEXT')
cw_yr = DatabaseColumn('cw_yr', '{} INTEGER NOT NULL')
d2_model_firmid = DatabaseColumn('d2_model_firmid', '')
ein = DatabaseColumn('ein', '{} TEXT NOT NULL')
emp_yr = DatabaseColumn('emp_yr', '{} INTEGER NOT NULL')
f_model = DatabaseColumn('f_model', '{} TEXT')
firm_name = DatabaseColumn('firm_name', '{} TEXT NOT NULL')
firmid = DatabaseColumn('firmid', '{} TEXT NOT NULL')
firmid_null = DatabaseColumn('firmid', '{} TEXT')
foreign_assg_flag = DatabaseColumn('foreign_assg_flag', '{} INTEGER')
grant_yr = DatabaseColumn('grant_yr', '{} INTEGER NOT NULL')
inv_seq = DatabaseColumn('inv_seq', '{} INTEGER NOT NULL')
model = DatabaseColumn('model', '{} TEXT')
model_origin = DatabaseColumn('model_origin', '{} TEXT NOT NULL')
mult_assg_flag = DatabaseColumn('multiple_assignee_flag', '{} INTEGER')
name = DatabaseColumn('name', '')
name_match_name = DatabaseColumn('name_match_name', '')
num_assg = DatabaseColumn('num_assg', '{} INTEGER')
num_inv = DatabaseColumn('num_inv', '{} INTEGER')
pass_num = DatabaseColumn('pass_num', '{} INTEGER NOT NULL')
pik = DatabaseColumn('pik', '{} TEXT NOT NULL')
pik_ein = DatabaseColumn('pik_ein', '')
pik_firmid = DatabaseColumn('pik_firmid', '')
pik_prdn = DatabaseColumn('pik_prdn', '')
prdn = DatabaseColumn('prdn', '{} TEXT NOT NULL')
sn_on_prdn_count = DatabaseColumn('sn_on_prdn_count', '{} INTEGER')
standard_name = DatabaseColumn('standard_name', '{} TEXT NOT NULL')
state = DatabaseColumn('state', '{} TEXT')
total_an_count = DatabaseColumn('total_an_count', '')
total_sn_count = DatabaseColumn('total_sn_count', '')
ui_firm_id = DatabaseColumn('ui_firm_id', '')
uniq_firmid = DatabaseColumn('uniq_firmid', '{} INTEGER')
us_assg_flag = DatabaseColumn('us_assg_flag', '{} INTEGER')
us_inv_flag = DatabaseColumn('us_inv_flag', '{} INTEGER')
uspto_name = DatabaseColumn('uspto_name', '{} TEXT')
uspto_pat_num = DatabaseColumn('uspto_pat_num', '{} TEXT NOT NULL')
xml_name = DatabaseColumn('xml_name', '{} TEXT NOT NULL')
xml_pat_num = DatabaseColumn('xml_pat_num', '{} TEXT NOT NULL')
valid_yr = DatabaseColumn('valid_year', '{} INTEGER NOT NULL')
year = DatabaseColumn('year', '{} INTEGER')
yr_diff = DatabaseColumn('yr_diff', '')
zip3 = DatabaseColumn('zip3', '{} INTEGER')
zip3_flag = DatabaseColumn('zip3_flag', '{} INTEGER')
